name: Run Jmeter File

on:
# Set your workflow to run every day of the week from Monday to Friday at 2:00 UTC
  schedule:
  - cron: "0 2 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  runPFTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.282'
          java-package: jdk
          architecture: x64
      - name: install jmeter
        env:
          JMETER_VERSION: 5.5
        run: |
          wget --no-verbose --no-check-certificate -O /tmp/apache-jmeter.tgz https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
          cd /tmp && tar -xvf apache-jmeter.tgz
          ln -S /tmp/apache-jmeter-$JMETER_VERSION /opt/jmeter
      - name: runjmeter
        run: |
          /opt/jmeter/bin/jmeter.sh \
          -t *.jmx \
          -l jmeter_logs/pf.jtl \
          -j jmeter_logs/pf.log

