name: Run Jmeter File

on:
  schedule:
  #- cron: "0 2 * * 1-5" # Set your workflow to run every day of the week from Monday to Friday at 2:00 UTC
  - cron: "45 6 * * 5"
  - cron: "59 4 * * 5"
  - cron: "10 5 * * 5" # Run at 3:10 pm SG time?

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "runPFTest"
  runPFTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.282'
          java-package: jdk
          architecture: x64
      - name: check JAVA version
        run:
          java -version
      - name: install jmeter
        env:
          JMETER_VERSION: 5.5
        run: |
          wget --no-verbose --no-check-certificate -O /tmp/apache-jmeter.tgz https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          cd /tmp && tar -xvf apache-jmeter.tgz
          echo "jmeter.save.saveservice.output_format=csv" >> /tmp/apache-jmeter-$JMETER_VERSION/bin/jmeter.properties
          echo "jmeter.save.saveservice.response_data.on_error=true" >> /tmp/apache-jmeter-$JMETER_VERSION/bin/jmeter.properties
          ln -s /tmp/apache-jmeter-$JMETER_VERSION /opt/jmeter
          mkdir -p -m 777 /home/runner/work/PerformanceTesting/PerformanceTesting/jmeter_report/PerfTestReport
          mkdir -p -m 777 /home/runner/work/PerformanceTesting/PerformanceTesting/jmeter_logs
          
      - name: run jmeter
        run: |
          /opt/jmeter/bin/jmeter.sh \
          -n \
          -t *.jmx \
          -l jmeter_logs/pf.jtl \
          -j jmeter_logs/pf.log \
          -e \
          -o jmeter_report/PerfTestReport
      
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: PerfTestReport
          path: /home/runner/work/PerformanceTesting/PerformanceTesting
